#############################################################################
# Makefile for building: FlowOrder
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  FlowOrder.pro
# Template: app
# Command: /home/yang/Qt5.2.1/5.2.1/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile FlowOrder.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -std=c++0x -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++ -I. -I. -I/home/yang/workspace/back/FlowOrder/../glog_0_3_3 -I/home/yang/workspace/back/FlowOrder/../boost_1_61_0/ -I/usr/local/include/mysql++ -I/usr/include/mysql
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/yang/Qt5.2.1/5.2.1/gcc_64
LIBS          = $(SUBLIBS) -L/home/yang/workspace/back/FlowOrder/lib/ -lmduserapi -ltraderapi -lthostmduserapi -lthosttraderapi -L/home/yang/workspace/back/FlowOrder/../glog_0_3_3/ -lglog -L/home/yang/workspace/back/FlowOrder/../boost_1_61_0/stage/lib/ -lboost_date_time -lboost_system -lboost_thread -lpthread -lboost_chrono -licui18n -licuuc -licudata -ldl -L/usr/lib64/mysql/ -lmysqlclient -L/usr/local/lib -lmysqlpp 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/yang/Qt5.2.1/5.2.1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		DataProcessor.cpp \
		MdSpi.cpp \
		property.cpp \
		TraderSpi.cpp \
		TimeProcesser.cpp \
		CSHFETraderSpi.cpp 
OBJECTS       = main.o \
		DataProcessor.o \
		MdSpi.o \
		property.o \
		TraderSpi.o \
		TimeProcesser.o \
		CSHFETraderSpi.o
DIST          = ../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/c++11.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/lex.prf \
		FlowOrder.pro \
		FlowOrder.pro
QMAKE_TARGET  = FlowOrder
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = FlowOrder


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: FlowOrder.pro ../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/c++11.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/lex.prf \
		FlowOrder.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile FlowOrder.pro
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/shell-unix.conf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/unix.conf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/linux.conf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/qconfig.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_post.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/c++11.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qml_debug.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/yacc.prf:
../../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/lex.prf:
FlowOrder.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile FlowOrder.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/FlowOrder1.0.0 || mkdir -p .tmp/FlowOrder1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FlowOrder1.0.0/ && (cd `dirname .tmp/FlowOrder1.0.0` && $(TAR) FlowOrder1.0.0.tar FlowOrder1.0.0 && $(COMPRESS) FlowOrder1.0.0.tar) && $(MOVE) `dirname .tmp/FlowOrder1.0.0`/FlowOrder1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FlowOrder1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp DataProcessor.h \
		lib/ThostFtdcTraderApi.h \
		lib/ThostFtdcUserApiStruct.h \
		lib/ThostFtdcUserApiDataType.h \
		TraderSpi.h \
		property.h \
		TimeProcesser.h \
		cshfe/FtdcTraderApi.h \
		cshfe/FtdcUserApiStruct.h \
		cshfe/FtdcUserApiDataType.h \
		CSHFETraderSpi.h \
		NetSniffer.cpp \
		MdSpi.h \
		lib/ThostFtdcMdApi.h \
		mysqlconnectpool.h \
		/usr/local/include/mysql++/mysql++.h \
		/usr/local/include/mysql++/connection.h \
		/usr/local/include/mysql++/common.h \
		/usr/include/mysql/mysql.h \
		/usr/include/mysql/mysql_version.h \
		/usr/include/mysql/mysql_com.h \
		/usr/include/mysql/mysql_time.h \
		/usr/include/mysql/my_list.h \
		/usr/include/mysql/typelib.h \
		/usr/include/mysql/my_alloc.h \
		/usr/local/include/mysql++/noexceptions.h \
		/usr/local/include/mysql++/options.h \
		/usr/local/include/mysql++/tcp_connection.h \
		/usr/local/include/mysql++/uds_connection.h \
		/usr/local/include/mysql++/wnp_connection.h \
		/usr/local/include/mysql++/cpool.h \
		/usr/local/include/mysql++/beemutex.h \
		/usr/local/include/mysql++/exceptions.h \
		/usr/local/include/mysql++/query.h \
		/usr/local/include/mysql++/qparms.h \
		/usr/local/include/mysql++/stadapter.h \
		/usr/local/include/mysql++/datetime.h \
		/usr/local/include/mysql++/comparable.h \
		/usr/local/include/mysql++/null.h \
		/usr/local/include/mysql++/sql_buffer.h \
		/usr/local/include/mysql++/refcounted.h \
		/usr/local/include/mysql++/type_info.h \
		/usr/local/include/mysql++/tiny_int.h \
		/usr/local/include/mysql++/querydef.h \
		/usr/local/include/mysql++/result.h \
		/usr/local/include/mysql++/field.h \
		/usr/local/include/mysql++/field_names.h \
		/usr/local/include/mysql++/field_types.h \
		/usr/local/include/mysql++/row.h \
		/usr/local/include/mysql++/mystring.h \
		/usr/local/include/mysql++/vallist.h \
		/usr/local/include/mysql++/manip.h \
		/usr/local/include/mysql++/myset.h \
		/usr/local/include/mysql++/stream2string.h \
		/usr/local/include/mysql++/sqlstream.h \
		/usr/local/include/mysql++/transaction.h \
		/usr/local/include/mysql++/insertpolicy.h \
		/usr/local/include/mysql++/scopedconnection.h \
		/usr/local/include/mysql++/sql_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

DataProcessor.o: DataProcessor.cpp DataProcessor.h \
		lib/ThostFtdcTraderApi.h \
		lib/ThostFtdcUserApiStruct.h \
		lib/ThostFtdcUserApiDataType.h \
		TraderSpi.h \
		property.h \
		TimeProcesser.h \
		cshfe/FtdcTraderApi.h \
		cshfe/FtdcUserApiStruct.h \
		cshfe/FtdcUserApiDataType.h \
		CSHFETraderSpi.h \
		mysqlconnectpool.h \
		/usr/local/include/mysql++/mysql++.h \
		/usr/local/include/mysql++/connection.h \
		/usr/local/include/mysql++/common.h \
		/usr/include/mysql/mysql.h \
		/usr/include/mysql/mysql_version.h \
		/usr/include/mysql/mysql_com.h \
		/usr/include/mysql/mysql_time.h \
		/usr/include/mysql/my_list.h \
		/usr/include/mysql/typelib.h \
		/usr/include/mysql/my_alloc.h \
		/usr/local/include/mysql++/noexceptions.h \
		/usr/local/include/mysql++/options.h \
		/usr/local/include/mysql++/tcp_connection.h \
		/usr/local/include/mysql++/uds_connection.h \
		/usr/local/include/mysql++/wnp_connection.h \
		/usr/local/include/mysql++/cpool.h \
		/usr/local/include/mysql++/beemutex.h \
		/usr/local/include/mysql++/exceptions.h \
		/usr/local/include/mysql++/query.h \
		/usr/local/include/mysql++/qparms.h \
		/usr/local/include/mysql++/stadapter.h \
		/usr/local/include/mysql++/datetime.h \
		/usr/local/include/mysql++/comparable.h \
		/usr/local/include/mysql++/null.h \
		/usr/local/include/mysql++/sql_buffer.h \
		/usr/local/include/mysql++/refcounted.h \
		/usr/local/include/mysql++/type_info.h \
		/usr/local/include/mysql++/tiny_int.h \
		/usr/local/include/mysql++/querydef.h \
		/usr/local/include/mysql++/result.h \
		/usr/local/include/mysql++/field.h \
		/usr/local/include/mysql++/field_names.h \
		/usr/local/include/mysql++/field_types.h \
		/usr/local/include/mysql++/row.h \
		/usr/local/include/mysql++/mystring.h \
		/usr/local/include/mysql++/vallist.h \
		/usr/local/include/mysql++/manip.h \
		/usr/local/include/mysql++/myset.h \
		/usr/local/include/mysql++/stream2string.h \
		/usr/local/include/mysql++/sqlstream.h \
		/usr/local/include/mysql++/transaction.h \
		/usr/local/include/mysql++/insertpolicy.h \
		/usr/local/include/mysql++/scopedconnection.h \
		/usr/local/include/mysql++/sql_types.h \
		/usr/local/include/mysql++/ssqls.h \
		DBTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataProcessor.o DataProcessor.cpp

MdSpi.o: MdSpi.cpp MdSpi.h \
		lib/ThostFtdcMdApi.h \
		lib/ThostFtdcUserApiStruct.h \
		lib/ThostFtdcUserApiDataType.h \
		lib/ThostFtdcTraderApi.h \
		TraderSpi.h \
		property.h \
		DataProcessor.h \
		TimeProcesser.h \
		cshfe/FtdcTraderApi.h \
		cshfe/FtdcUserApiStruct.h \
		cshfe/FtdcUserApiDataType.h \
		CSHFETraderSpi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MdSpi.o MdSpi.cpp

property.o: property.cpp property.h \
		lib/ThostFtdcTraderApi.h \
		lib/ThostFtdcUserApiStruct.h \
		lib/ThostFtdcUserApiDataType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o property.o property.cpp

TraderSpi.o: TraderSpi.cpp lib/ThostFtdcTraderApi.h \
		lib/ThostFtdcUserApiStruct.h \
		lib/ThostFtdcUserApiDataType.h \
		TraderSpi.h \
		property.h \
		DataProcessor.h \
		TimeProcesser.h \
		cshfe/FtdcTraderApi.h \
		cshfe/FtdcUserApiStruct.h \
		cshfe/FtdcUserApiDataType.h \
		CSHFETraderSpi.h \
		TradeProcessor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TraderSpi.o TraderSpi.cpp

TimeProcesser.o: TimeProcesser.cpp TimeProcesser.h \
		property.h \
		lib/ThostFtdcTraderApi.h \
		lib/ThostFtdcUserApiStruct.h \
		lib/ThostFtdcUserApiDataType.h \
		DataProcessor.h \
		TraderSpi.h \
		cshfe/FtdcTraderApi.h \
		cshfe/FtdcUserApiStruct.h \
		cshfe/FtdcUserApiDataType.h \
		CSHFETraderSpi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TimeProcesser.o TimeProcesser.cpp

CSHFETraderSpi.o: CSHFETraderSpi.cpp CSHFETraderSpi.h \
		cshfe/FtdcTraderApi.h \
		cshfe/FtdcUserApiStruct.h \
		cshfe/FtdcUserApiDataType.h \
		DataProcessor.h \
		lib/ThostFtdcTraderApi.h \
		lib/ThostFtdcUserApiStruct.h \
		lib/ThostFtdcUserApiDataType.h \
		TraderSpi.h \
		property.h \
		TimeProcesser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CSHFETraderSpi.o CSHFETraderSpi.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

